@tool
extends EditorPlugin

var export_plugin: Godot2AmigaExportPlugin

func _enter_tree() -> void:
export_plugin = Godot2AmigaExportPlugin.new()
add_export_plugin(export_plugin)

func _exit_tree() -> void:
remove_export_plugin(export_plugin)
export_plugin = null

class Godot2AmigaExportPlugin:
extends EditorExportPlatform

```
func _get_name() -> String:
	return "Amiga"

func _get_os_name() -> String:
	return "Amiga"

func _get_logo() -> Texture2D:
	return null

func _poll_export() -> bool:
	return true

func _get_platform_features() -> PackedStringArray:
	return PackedStringArray(["amiga", "godot2amiga"])

func _get_binary_extensions(preset: EditorExportPreset) -> PackedStringArray:
	return PackedStringArray([""])

func _get_export_options() -> Array[Dictionary]:
	return [
		{
			"name": "target_profile",
			"default_value": "Amiga 500 (OCS, 68000, 1MB)",
			"property_hint": PROPERTY_HINT_ENUM,
			"hint_string": "Amiga 500 (OCS, 68000, 1MB),Amiga 600 (ECS),Amiga 1200 (AGA),CD32,RTG"
		},
		{
			"name": "output_folder",
			"default_value": "build/amiga"
		}
	]

func _export_project(
	preset: EditorExportPreset,
	debug: bool,
	path: String,
	flags: int
) -> Error:
	var output_folder := preset.get("output_folder")
	if output_folder == "":
		output_folder = "build/amiga"

	var absolute_output := ProjectSettings.globalize_path("res://" + output_folder)
	DirAccess.make_dir_recursive_absolute(absolute_output)

	_write_text_file(
		absolute_output + "/README_BUILD.txt",
		"Godot2Amiga export output\n\nThis folder was generated by the Godot2Amiga exporter.\n"
	)

	_write_text_file(
		absolute_output + "/main.c",
		_get_main_c()
	)

	_write_text_file(
		absolute_output + "/Makefile",
		_get_makefile()
	)

	print("Godot2Amiga export complete: " + absolute_output)

	return OK

func _write_text_file(file_path: String, contents: String) -> void:
	var file := FileAccess.open(file_path, FileAccess.WRITE)
	if file == null:
		push_error("Could not write file: " + file_path)
		return

	file.store_string(contents)
	file.close()

func _get_main_c() -> String:
	return """/*
```

* Generated by Godot2Amiga
  */

#include <stdio.h>

int main(void) {
printf("Hello from Godot2Amiga!\n");
return 0;
}
"""

```
func _get_makefile() -> String:
	return """# Generated by Godot2Amiga
```

CC=m68k-amigaos-gcc
CFLAGS=-O2
TARGET=godot2amiga_demo

all:
$(CC) $(CFLAGS) -o $(TARGET) main.c

clean:
rm -f $(TARGET)
"""
