"""Compose complete ACE main.c source from tested generation fragments."""

from __future__ import annotations

from dataclasses import dataclass

from g2a.ace_main_fragments import AceMainFragments


class AceMainComposerError(ValueError):
    """Raised when an ACE main program configuration is invalid."""


@dataclass(frozen=True)
class AceMainPlatformConfig:
    """ACE platform settings required by generated main.c."""

    palette_path: str
    bitplane_depth: int
    color_count: int
    interleaved: bool = True
    double_buffered: bool = False

    def __post_init__(self) -> None:
        if not self.palette_path:
            raise AceMainComposerError("palette_path must be non-empty")
        if self.bitplane_depth <= 0:
            raise AceMainComposerError("bitplane_depth must be positive")
        if self.color_count <= 0:
            raise AceMainComposerError("color_count must be positive")
        if self.color_count > (1 << self.bitplane_depth):
            raise AceMainComposerError("color_count exceeds bitplane capacity")

    @property
    def bitmap_flags(self) -> str:
        if self.interleaved:
            return "BMF_CLEAR | BMF_INTERLEAVED"
        return "BMF_CLEAR"

    @property
    def double_buffer_value(self) -> int:
        return 1 if self.double_buffered else 0


@dataclass(frozen=True)
class AceMainRuntimeSections:
    """Optional runtime-owned source sections.

    The existing animation runtime generator can supply declarations,
    initialization, per-frame work, and cleanup without duplicating its
    internal state or timing logic in the composer.
    """

    declarations: str = ""
    initialization: str = ""
    process_before_ticks: str = ""
    process_after_draw: str = ""
    cleanup: str = ""


@dataclass(frozen=True)
class AceMainSource:
    source: str
    platform: AceMainPlatformConfig


def _join_sections(*sections: str) -> str:
    return "\n\n".join(section.strip() for section in sections if section.strip())


def compose_ace_main_c(
    platform: AceMainPlatformConfig,
    fragments: AceMainFragments,
    *,
    runtime: AceMainRuntimeSections | None = None,
    generated_comment: str = ("Generated by Godot2Amiga - M8.1 unified main composer."),
) -> AceMainSource:
    """Compose a complete ACE generic-main source file."""
    runtime = runtime or AceMainRuntimeSections()

    declarations = _join_sections(
        fragments.declarations,
        runtime.declarations,
    )
    initialization = _join_sections(
        fragments.bitmap_loads,
        runtime.initialization,
    )
    process = _join_sections(
        runtime.process_before_ticks,
        fragments.animation_ticks,
        fragments.draw_steps,
        runtime.process_after_draw,
    )
    cleanup = _join_sections(
        runtime.cleanup,
        fragments.cleanup,
    )

    source = f"""/* {generated_comment} */

#include "generated_project.h"

#include <ace/managers/blit.h>
#include <ace/managers/key.h>
#include <ace/managers/system.h>
#include <ace/managers/viewport/simplebuffer.h>
#include <ace/utils/bitmap.h>
#include <ace/utils/extview.h>
#include <ace/utils/palette.h>

static tView *s_pView;
static tVPort *s_pViewport;
static tSimpleBufferManager *s_pBuffer;
{declarations}
static UBYTE s_isRunning;

#define GENERIC_MAIN_LOOP_CONDITION s_isRunning
#include <ace/generic/main.h>

void genericCreate(void) {{
    keyCreate();

    s_pView = viewCreate(0, TAG_DONE);

    s_pViewport = vPortCreate(
        0,
        TAG_VPORT_VIEW,
        s_pView,
        TAG_VPORT_BPP,
        {platform.bitplane_depth},
        TAG_DONE
    );

    s_pBuffer = simpleBufferCreate(
        0,
        TAG_SIMPLEBUFFER_VPORT,
        s_pViewport,
        TAG_SIMPLEBUFFER_BITMAP_FLAGS,
        {platform.bitmap_flags},
        TAG_SIMPLEBUFFER_IS_DBLBUF,
        {platform.double_buffer_value},
        TAG_DONE
    );

    paletteLoadFromPath(
        "{platform.palette_path}",
        s_pViewport->pPalette,
        {platform.color_count}
    );

{initialization}

    s_isRunning = 1;
    systemUnuse();
    viewLoad(s_pView);
}}

void genericProcess(void) {{
    keyProcess();

    if (keyUse(KEY_ESCAPE)) {{
        s_isRunning = 0;
        return;
    }}

{process}

    vPortWaitForEnd(s_pViewport);
}}

void genericDestroy(void) {{
    systemUse();

{cleanup}

    viewDestroy(s_pView);
    keyDestroy();
}}
"""

    return AceMainSource(
        source=source,
        platform=platform,
    )


__all__ = [
    "AceMainComposerError",
    "AceMainPlatformConfig",
    "AceMainRuntimeSections",
    "AceMainSource",
    "compose_ace_main_c",
]
