"""Generate an ACE-oriented C project from a validated .g2a package."""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any

from rich.console import Console

from g2a.project import load_package
from g2a.validate import validate_package

EXIT_OK = 0
EXIT_INVALID_PACKAGE = 1
EXIT_OUTPUT_EXISTS = 2
EXIT_BUILD_FAILED = 3


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="g2a-build",
        description="Generate an ACE-oriented C project from a .g2a package.",
    )
    parser.add_argument("package", type=Path, help="Path to a .g2a directory")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        required=True,
        help="Directory where the generated C project will be written",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace the output directory when it already exists",
    )
    return parser


def _c_string(value: str) -> str:
    """Escape a Python string for use as a C string literal."""
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def _json_text(value: Any) -> str:
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def _write_text(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8", newline="\n")


def _render_main_c(project_name: str) -> str:
    escaped_name = _c_string(project_name)
    return f"""/* Generated by Godot2Amiga. */

#include "generated_project.h"

#include <stdio.h>

int main(void) {{
    puts("Godot2Amiga: {escaped_name}");
    return 0;
}}
"""


def _render_generated_header(project_name: str, project_id: str) -> str:
    escaped_name = _c_string(project_name)
    escaped_id = _c_string(project_id)
    return f"""#pragma once

#define G2A_PROJECT_NAME "{escaped_name}"
#define G2A_PROJECT_ID "{escaped_id}"
"""


def _render_generated_source() -> str:
    return """/* Generated by Godot2Amiga. */

#include "generated_project.h"

const char *g2a_project_name(void) {
    return G2A_PROJECT_NAME;
}

const char *g2a_project_id(void) {
    return G2A_PROJECT_ID;
}
"""


def _render_cmake(project_id: str) -> str:
    return f"""cmake_minimum_required(VERSION 3.20)

project({project_id} C)

add_executable(${{PROJECT_NAME}}
    src/main.c
    src/generated_project.c
)

target_include_directories(${{PROJECT_NAME}} PRIVATE include)
"""


def _render_makefile(project_id: str) -> str:
    return f"""CC ?= m68k-amigaos-gcc
CFLAGS ?= -O2 -Wall -Wextra -Iinclude
TARGET ?= {project_id}

SOURCES := src/main.c src/generated_project.c

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(SOURCES)
	$(CC) $(CFLAGS) -o $@ $(SOURCES)

clean:
	rm -f $(TARGET)
"""


def generate_project(package_path: Path, output_path: Path, *, force: bool = False) -> int:
    """Validate a .g2a package and generate deterministic backend output."""
    package_path = package_path.resolve()
    output_path = output_path.resolve()

    issues = validate_package(package_path)
    if issues:
        return EXIT_INVALID_PACKAGE

    if output_path.exists():
        if not force:
            return EXIT_OUTPUT_EXISTS
        if output_path.is_dir():
            shutil.rmtree(output_path)
        else:
            output_path.unlink()

    package = load_package(package_path)
    project_name = package.project.name
    project_id = package.project.project_id

    output_path.mkdir(parents=True)
    (output_path / "assets").mkdir()
    (output_path / "include").mkdir()
    (output_path / "src").mkdir()

    _write_text(output_path / "src" / "main.c", _render_main_c(project_name))
    _write_text(
        output_path / "src" / "generated_project.c",
        _render_generated_source(),
    )
    _write_text(
        output_path / "include" / "generated_project.h",
        _render_generated_header(project_name, project_id),
    )
    _write_text(output_path / "CMakeLists.txt", _render_cmake(project_id))
    _write_text(output_path / "Makefile", _render_makefile(project_id))

    build_info = {
        "backend": "ace",
        "format": package.manifest.format,
        "format_version": package.manifest.format_version,
        "generator": {
            "name": "g2a-build",
            "version": "0.2.0",
        },
        "project": {
            "id": project_id,
            "name": project_name,
            "main_scene": package.project.main_scene,
        },
        "target": package.export_profile,
    }
    _write_text(output_path / "BUILD_INFO.json", _json_text(build_info))

    return EXIT_OK


def run(
    package_path: Path,
    output_path: Path,
    *,
    force: bool = False,
    console: Console | None = None,
) -> int:
    console = console or Console()

    issues = validate_package(package_path)
    if issues:
        console.print(f"[red]INVALID:[/red] {package_path.resolve()}", highlight=False)
        for issue in issues:
            console.print(f"  - {issue.render()}", highlight=False)
        return EXIT_INVALID_PACKAGE

    result = generate_project(package_path, output_path, force=force)

    if result == EXIT_OUTPUT_EXISTS:
        console.print(
            f"[red]ERROR:[/red] output already exists: {output_path.resolve()}",
            highlight=False,
        )
        console.print("Use --force to replace it.")
        return result

    if result != EXIT_OK:
        console.print("[red]ERROR:[/red] project generation failed.")
        return EXIT_BUILD_FAILED

    console.print(f"[green]GENERATED:[/green] {output_path.resolve()}", highlight=False)
    return EXIT_OK


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return run(args.package, args.output, force=args.force)


if __name__ == "__main__":
    raise SystemExit(main())
