"""Render a complete ACE main.c for AnimatedSprite2D scenes."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from g2a.runtime_animated_codegen import render_animated_runtime_unit
from g2a.runtime_animated_scene import RuntimeAnimatedSceneSprite


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _palette_contract(package: Path) -> tuple[str, int, int, bool]:
    manifest = _load_json(package / "assets/assets.json")
    palettes = manifest.get("palettes", [])
    bitmaps = manifest.get("bitmaps", [])
    if not isinstance(palettes, list) or len(palettes) != 1:
        raise ValueError("animated runtime requires exactly one palette")
    if not isinstance(bitmaps, list) or not bitmaps:
        raise ValueError("animated runtime requires bitmap assets")
    palette = palettes[0]
    palette_output = palette.get("output")
    palette_source = palette.get("source")
    if not isinstance(palette_output, str) or not palette_output:
        raise ValueError("palette has no output path")
    if not isinstance(palette_source, str) or not palette_source:
        raise ValueError("palette has no source path")
    color_count = 0
    for raw_line in (package / palette_source).read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if (
            not line
            or line.startswith("#")
            or line.startswith("GIMP Palette")
            or line.startswith("Name:")
            or line.startswith("Columns:")
        ):
            continue
        fields = line.split()
        if len(fields) >= 3:
            try:
                channels = tuple(int(field) for field in fields[:3])
            except ValueError:
                continue
            if all(0 <= channel <= 255 for channel in channels):
                color_count += 1
    if not 1 <= color_count <= 32:
        raise ValueError("animated palette must contain 1..32 colors")
    bpp = max(1, (color_count - 1).bit_length())
    layouts = {entry.get("interleaved", False) for entry in bitmaps if isinstance(entry, dict)}
    if len(layouts) != 1:
        raise ValueError("all frame bitmaps must share one layout")
    interleaved = next(iter(layouts))
    if not isinstance(interleaved, bool):
        raise ValueError("bitmap interleaved must be boolean")
    return f"data/{palette_output}", bpp, 1 << bpp, interleaved


def render_animated_scene_main_c(
    package: Path, sprites: tuple[RuntimeAnimatedSceneSprite, ...]
) -> str:
    if not sprites:
        raise ValueError("animated scene requires at least one sprite")
    package = package.expanduser().resolve()
    palette_path, bpp, color_count, interleaved = _palette_contract(package)
    unit = render_animated_runtime_unit(sprites)
    bitmap_flags = "BMF_CLEAR | BMF_INTERLEAVED" if interleaved else "BMF_CLEAR"
    return f'''/* Generated by Godot2Amiga - AnimatedSprite2D runtime. */

#include "generated_project.h"
#include <ace/managers/blit.h>
#include <ace/managers/key.h>
#include <ace/managers/system.h>
#include <ace/managers/viewport/simplebuffer.h>
#include <ace/utils/bitmap.h>
#include <ace/utils/extview.h>
#include <ace/utils/palette.h>

static tView *s_pView;
static tVPort *s_pViewport;
static tSimpleBufferManager *s_pBuffer;
static UBYTE s_isRunning;

{unit.declarations}

#define GENERIC_MAIN_LOOP_CONDITION s_isRunning
#include <ace/generic/main.h>

void genericCreate(void) {{
    keyCreate();
    s_pView = viewCreate(0, TAG_DONE);
    s_pViewport = vPortCreate(0, TAG_VPORT_VIEW, s_pView, TAG_VPORT_BPP, {bpp}, TAG_DONE);
    s_pBuffer = simpleBufferCreate(0, TAG_SIMPLEBUFFER_VPORT, s_pViewport,
        TAG_SIMPLEBUFFER_BITMAP_FLAGS, {bitmap_flags}, TAG_SIMPLEBUFFER_IS_DBLBUF, 0, TAG_DONE);
    paletteLoadFromPath("{palette_path}", s_pViewport->pPalette, {color_count});

{unit.initialization}

    s_isRunning = 1;
    systemUnuse();
    viewLoad(s_pView);
}}

void genericProcess(void) {{
    keyProcess();
    if(keyUse(KEY_ESCAPE)) {{
        s_isRunning = 0;
        return;
    }}
    vPortWaitForEnd(s_pViewport);
    bitmapClear(s_pBuffer->pBack, 0);

{unit.tick_loop}

{unit.render_loop}

    blitWait();
}}

void genericDestroy(void) {{
    systemUse();

{unit.cleanup}

    viewDestroy(s_pView);
    keyDestroy();
}}
'''


__all__ = ["render_animated_scene_main_c"]
