"""Generate a minimal .g2a package from a Godot text scene."""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from g2a.gimp_palette import generate_m5_assets
from g2a.godot_tscn import parse_tscn, to_g2a_scene_document
from g2a.tscn_assets import import_texture_assets

FORMAT_VERSION = "0.1.0"
GENERATOR_VERSION = "0.7.2"

EXIT_OK = 0
EXIT_OUTPUT_EXISTS = 2


@dataclass(frozen=True)
class TscnPackageConfig:
    source: Path
    output: Path
    project_name: str | None = None
    project_id: str | None = None
    project_root: Path | None = None
    force: bool = False

    @property
    def resolved_source(self) -> Path:
        return self.source.expanduser().resolve()

    @property
    def resolved_output(self) -> Path:
        return self.output.expanduser().resolve()


def _slugify(value: str) -> str:
    chars: list[str] = []
    previous_dash = False
    for character in value.strip().lower():
        if character.isascii() and character.isalnum():
            chars.append(character)
            previous_dash = False
        elif not previous_dash:
            chars.append("-")
            previous_dash = True
    return "".join(chars).strip("-") or "unnamed-project"


def _json_text(value: Any) -> str:
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def _write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        _json_text(value),
        encoding="utf-8",
        newline="\n",
    )


def _prepare_output(config: TscnPackageConfig) -> int:
    output = config.resolved_output

    if output.exists():
        if not config.force:
            return EXIT_OUTPUT_EXISTS
        if output.is_dir():
            shutil.rmtree(output)
        else:
            output.unlink()

    for directory in (
        "scenes",
        "assets",
        "scripts",
        "resources",
        "metadata",
        "diagnostics",
    ):
        (output / directory).mkdir(parents=True, exist_ok=True)

    return EXIT_OK


def generate_tscn_package(config: TscnPackageConfig) -> int:
    source = config.resolved_source
    if not source.is_file():
        raise ValueError(f"TSCN source does not exist: {source}")
    if source.suffix.lower() != ".tscn":
        raise ValueError("TSCN source must use the .tscn extension")

    prepare_result = _prepare_output(config)
    if prepare_result != EXIT_OK:
        return prepare_result

    project_name = config.project_name or source.stem.replace("_", " ").title()
    project_id = config.project_id or _slugify(project_name)
    scene_id = _slugify(source.stem)
    scene_path = f"scenes/{scene_id}.json"

    parsed_scene = parse_tscn(source)
    if config.project_root is None:
        imported_textures = ()
    else:
        imported_textures = import_texture_assets(
            parsed_scene,
            project_root=(config.project_root.expanduser().resolve()),
            package_root=config.resolved_output,
        )
    scene_document = to_g2a_scene_document(
        parsed_scene,
        scene_id=scene_id,
        source=str(source),
    )

    manifest = {
        "$schema": ("https://godot2amiga.org/schemas/g2a/manifest.schema.json"),
        "format": "g2a",
        "format_version": FORMAT_VERSION,
        "generator": {
            "name": "g2a-tscn",
            "version": GENERATOR_VERSION,
            "godot_version": "0.0.0",
        },
    }

    project = {
        "$schema": ("https://godot2amiga.org/schemas/g2a/project.schema.json"),
        "id": project_id,
        "name": project_name,
        "main_scene": scene_path,
        "source": {
            "engine": "godot",
            "project_file": "unknown",
            "main_scene": str(source),
        },
    }

    export_profile = {
        "$schema": ("https://godot2amiga.org/schemas/g2a/export-profile.schema.json"),
        "id": "amiga500-ocs-pal",
        "machine": "Amiga 500",
        "chipset": "OCS",
        "cpu": "68000",
        "video_standard": "PAL",
        "chip_ram_kib": 512,
        "fast_ram_kib": 0,
        "runtime": "ACE",
    }

    diagnostics = {
        "$schema": ("https://godot2amiga.org/schemas/g2a/diagnostics.schema.json"),
        "errors": [],
        "warnings": [],
        "notes": [
            {
                "code": "G2A-M72A2-HOST-TSCN-IMPORT",
                "message": (
                    "Package generated by the host-side TSCN importer. "
                    "Texture copying and conversion are not included."
                ),
                "source": str(source),
            }
        ],
    }

    output = config.resolved_output
    _write_json(output / "manifest.json", manifest)
    _write_json(output / "project.json", project)
    _write_json(output / "export_profile.json", export_profile)
    _, asset_manifest = generate_m5_assets(
        imported_textures,
        package_root=output,
    )
    _write_json(
        output / "assets/assets.json",
        asset_manifest,
    )
    _write_json(output / scene_path, scene_document)
    _write_json(
        output / "diagnostics/diagnostics.json",
        diagnostics,
    )

    return EXIT_OK


__all__ = [
    "EXIT_OK",
    "EXIT_OUTPUT_EXISTS",
    "TscnPackageConfig",
    "generate_tscn_package",
]
