@tool
extends RefCounted

const GENERATED_FILES := {
    "main.c": """/*
 * Generated by Godot2Amiga.
 *
 * This is an M1 project skeleton, not yet a complete scene conversion.
 */

#include <stdio.h>

int main(void) {
    puts("Hello from Godot2Amiga!");
    return 0;
}
""",
    "Makefile": """CC ?= m68k-amigaos-gcc
CFLAGS ?= -O2 -Wall -Wextra
TARGET ?= godot2amiga-demo

.PHONY: all clean

all: $(TARGET)

$(TARGET): main.c
\t$(CC) $(CFLAGS) -o $@ $<

clean:
\trm -f $(TARGET)
""",
    "README_BUILD.txt": """Godot2Amiga generated project skeleton
=======================================

Generated files:
- main.c
- Makefile
- project_manifest.json

The default Makefile expects an m68k-amigaos-gcc cross compiler.

This M1 skeleton proves that the Godot editor plugin can generate deterministic
native-project output. It does not yet translate Godot scenes or link ACE.
"""
}


func generate(output_directory: String) -> Error:
    var directory_error := DirAccess.make_dir_recursive_absolute(
        ProjectSettings.globalize_path(output_directory)
    )
    if directory_error != OK:
        push_error(
            "Godot2Amiga: could not create output directory '%s' (error %d)."
            % [output_directory, directory_error]
        )
        return directory_error

    for filename: String in GENERATED_FILES:
        var write_error := _write_text_file(
            output_directory.path_join(filename),
            GENERATED_FILES[filename]
        )
        if write_error != OK:
            return write_error

    var manifest := {
        "format": "godot2amiga-project-manifest",
        "format_version": 1,
        "generator_version": "0.1.0",
        "godot_project_name": str(
            ProjectSettings.get_setting("application/config/name", "Unnamed project")
        ),
        "main_scene": str(
            ProjectSettings.get_setting("application/run/main_scene", "")
        ),
        "target": {
            "platform": "amiga",
            "chipset": "ocs",
            "runtime": "ace",
            "video_standard": "pal"
        }
    }

    var manifest_error := _write_text_file(
        output_directory.path_join("project_manifest.json"),
        JSON.stringify(manifest, "\t") + "\n"
    )
    if manifest_error != OK:
        return manifest_error

    return OK


func _write_text_file(path: String, contents: String) -> Error:
    var file := FileAccess.open(path, FileAccess.WRITE)
    if file == null:
        var open_error := FileAccess.get_open_error()
        push_error(
            "Godot2Amiga: could not open '%s' for writing (error %d)."
            % [path, open_error]
        )
        return open_error

    file.store_string(contents)
    file.close()
    return OK
