"""Generate the M6.0c static bitmap runtime using ACE generic main."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ASSET_MANIFEST = Path("assets/assets.json")


@dataclass(frozen=True)
class RuntimeAssetDemo:
    """One converted bitmap loaded directly into the screen buffer."""

    palette_path: str
    bitmap_path: str
    bpp: int
    color_count: int
    x: int
    y: int
    interleaved: bool


def _load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def load_runtime_asset_demo(
    package: Path,
) -> RuntimeAssetDemo | None:
    """Load optional runtime_demo settings from assets/assets.json."""
    manifest_path = package.expanduser().resolve() / ASSET_MANIFEST
    if not manifest_path.is_file():
        return None

    value = _load_json(manifest_path)
    if not isinstance(value, dict):
        raise ValueError("asset manifest must contain a JSON object")

    demo = value.get("runtime_demo")
    if demo is None:
        return None
    if not isinstance(demo, dict):
        raise ValueError("runtime_demo must be an object")

    palette_id = demo.get("palette")
    bitmap_id = demo.get("bitmap")
    bpp = demo.get("bpp")
    x = demo.get("x", 0)
    y = demo.get("y", 0)

    if not isinstance(palette_id, str) or not palette_id:
        raise ValueError("runtime_demo.palette must be a non-empty string")
    if not isinstance(bitmap_id, str) or not bitmap_id:
        raise ValueError("runtime_demo.bitmap must be a non-empty string")
    if not isinstance(bpp, int) or not 1 <= bpp <= 5:
        raise ValueError("runtime_demo.bpp must be an integer from 1 to 5")
    if not isinstance(x, int) or x < 0:
        raise ValueError("runtime_demo.x must be a non-negative integer")
    if not isinstance(y, int) or y < 0:
        raise ValueError("runtime_demo.y must be a non-negative integer")

    palettes = value.get("palettes", [])
    bitmaps = value.get("bitmaps", [])

    if not isinstance(palettes, list):
        raise ValueError("asset palettes must be an array")
    if not isinstance(bitmaps, list):
        raise ValueError("asset bitmaps must be an array")

    palette = next(
        (entry for entry in palettes if isinstance(entry, dict) and entry.get("id") == palette_id),
        None,
    )
    bitmap = next(
        (entry for entry in bitmaps if isinstance(entry, dict) and entry.get("id") == bitmap_id),
        None,
    )

    if palette is None:
        raise ValueError(f"runtime_demo references unknown palette id: {palette_id}")
    if bitmap is None:
        raise ValueError(f"runtime_demo references unknown bitmap id: {bitmap_id}")

    palette_output = palette.get("output")
    bitmap_output = bitmap.get("output")
    interleaved = bitmap.get("interleaved", False)

    if not isinstance(palette_output, str) or not palette_output:
        raise ValueError("runtime demo palette has no output path")
    if not isinstance(bitmap_output, str) or not bitmap_output:
        raise ValueError("runtime demo bitmap has no output path")
    if not isinstance(interleaved, bool):
        raise ValueError("runtime demo bitmap interleaved flag must be boolean")

    return RuntimeAssetDemo(
        palette_path=f"data/{palette_output}",
        bitmap_path=f"data/{bitmap_output}",
        bpp=bpp,
        color_count=1 << bpp,
        x=x,
        y=y,
        interleaved=interleaved,
    )


def render_runtime_asset_main_c(
    demo: RuntimeAssetDemo,
) -> str:
    """Render static bitmap code using ACE generic main lifecycle."""
    bitmap_flags = "BMF_CLEAR | BMF_INTERLEAVED" if demo.interleaved else "BMF_CLEAR"

    return f"""/* Generated by Godot2Amiga - M6.0c static bitmap. */

#include "generated_project.h"

#include <ace/managers/key.h>
#include <ace/managers/system.h>
#include <ace/managers/viewport/simplebuffer.h>
#include <ace/utils/bitmap.h>
#include <ace/utils/extview.h>
#include <ace/utils/palette.h>

static tView *s_pView;
static tVPort *s_pViewport;
static tSimpleBufferManager *s_pBuffer;
static UBYTE s_isRunning;

#define GENERIC_MAIN_LOOP_CONDITION s_isRunning
#include <ace/generic/main.h>

void genericCreate(void) {{
    keyCreate();

    s_pView = viewCreate(
        0,
        TAG_DONE
    );

    s_pViewport = vPortCreate(
        0,
        TAG_VPORT_VIEW,
        s_pView,
        TAG_VPORT_BPP,
        {demo.bpp},
        TAG_DONE
    );

    s_pBuffer = simpleBufferCreate(
        0,
        TAG_SIMPLEBUFFER_VPORT,
        s_pViewport,
        TAG_SIMPLEBUFFER_BITMAP_FLAGS,
        {bitmap_flags},
        TAG_SIMPLEBUFFER_IS_DBLBUF,
        0,
        TAG_DONE
    );

    paletteLoadFromPath(
        "{demo.palette_path}",
        s_pViewport->pPalette,
        {demo.color_count}
    );

    bitmapLoadFromPath(
        s_pBuffer->pBack,
        "{demo.bitmap_path}",
        {demo.x},
        {demo.y}
    );

    s_isRunning = 1;

    systemUnuse();
    viewLoad(s_pView);
}}

void genericProcess(void) {{
    keyProcess();

    if (keyUse(KEY_ESCAPE)) {{
        s_isRunning = 0;
        return;
    }}

    vPortWaitForEnd(s_pViewport);
}}

void genericDestroy(void) {{
    systemUse();

    viewDestroy(s_pView);
    keyDestroy();
}}
"""


__all__ = [
    "RuntimeAssetDemo",
    "load_runtime_asset_demo",
    "render_runtime_asset_main_c",
]
