"""Generate ACE C for a normalized multi-sprite runtime scene."""

from __future__ import annotations

import re
from dataclasses import dataclass

from g2a.backend.ace.blit_plan import plan_sprite_blit
from g2a.backend.ace.runtime_scene import RuntimeScene, RuntimeSprite


@dataclass(frozen=True)
class RuntimeBitmap:
    """One unique bitmap resource loaded by the generated runtime."""

    texture_id: str
    bitmap_path: str
    variable_name: str


def _identifier(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if not normalized:
        normalized = "bitmap"
    if normalized[0].isdigit():
        normalized = f"bitmap_{normalized}"
    return normalized


def unique_runtime_bitmaps(
    scene: RuntimeScene,
) -> tuple[RuntimeBitmap, ...]:
    """Deduplicate bitmap loads while preserving first-use order."""
    result: list[RuntimeBitmap] = []
    seen: set[str] = set()

    for sprite in scene.sprites:
        if sprite.texture_id in seen:
            continue
        seen.add(sprite.texture_id)
        result.append(
            RuntimeBitmap(
                texture_id=sprite.texture_id,
                bitmap_path=sprite.bitmap_path,
                variable_name="s_pBitmap_" + _identifier(sprite.texture_id),
            )
        )

    return tuple(result)


def _validate_scene_compatibility(
    scene: RuntimeScene,
) -> tuple[str, int, int, bool]:
    if not scene.sprites:
        raise ValueError("multi-sprite runtime requires at least one Sprite2D")

    first = scene.sprites[0]
    expected = (
        first.palette_path,
        first.bpp,
        first.color_count,
        first.interleaved,
    )

    for sprite in scene.sprites[1:]:
        actual = (
            sprite.palette_path,
            sprite.bpp,
            sprite.color_count,
            sprite.interleaved,
        )
        if actual != expected:
            raise ValueError(
                "M6.2 requires all sprites to use one palette, bitplane depth, and bitmap layout"
            )

    return expected


def _bitmap_for_sprite(
    sprite: RuntimeSprite,
    bitmaps: tuple[RuntimeBitmap, ...],
) -> RuntimeBitmap:
    for bitmap in bitmaps:
        if bitmap.texture_id == sprite.texture_id:
            return bitmap
    raise ValueError(f"no runtime bitmap for texture {sprite.texture_id!r}")


def _render_bitmap_load(bitmap: RuntimeBitmap) -> str:
    return f'''    {bitmap.variable_name} = bitmapCreateFromPath(
        "{bitmap.bitmap_path}",
        0
    );

    if (!{bitmap.variable_name}) {{
        s_isRunning = 0;
        return;
    }}'''


def _render_sprite_blit(
    sprite: RuntimeSprite,
    bitmap: RuntimeBitmap,
) -> str | None:
    if sprite.width is None or sprite.height is None:
        return f"""    blitCopy(
        {bitmap.variable_name},
        0,
        0,
        s_pBuffer->pBack,
        {sprite.x},
        {sprite.y},
        bitmapGetByteWidth({bitmap.variable_name}) * 8,
        {bitmap.variable_name}->Rows,
        MINTERM_COPY
    );"""

    plan = plan_sprite_blit(
        sprite_x=sprite.x,
        sprite_y=sprite.y,
        sprite_width=sprite.width,
        sprite_height=sprite.height,
        viewport_width=320,
        viewport_height=256,
    )
    if plan is None:
        return None

    return f"""    blitCopy(
        {bitmap.variable_name},
        {plan.source_x},
        {plan.source_y},
        s_pBuffer->pBack,
        {plan.destination_x},
        {plan.destination_y},
        {plan.width},
        {plan.height},
        MINTERM_COPY
    );"""


def _render_bitmap_destroy(bitmap: RuntimeBitmap) -> str:
    return f"""    if ({bitmap.variable_name}) {{
        bitmapDestroy({bitmap.variable_name});
    }}"""


def render_runtime_scene_main_c(scene: RuntimeScene) -> str:
    """Render ACE generic-main code for multiple static sprites."""
    palette_path, bpp, color_count, interleaved = _validate_scene_compatibility(scene)
    bitmaps = unique_runtime_bitmaps(scene)

    bitmap_flags = "BMF_CLEAR | BMF_INTERLEAVED" if interleaved else "BMF_CLEAR"
    bitmap_declarations = "\n".join(
        f"static tBitMap *{bitmap.variable_name};" for bitmap in bitmaps
    )
    bitmap_loads = "\n\n".join(_render_bitmap_load(bitmap) for bitmap in bitmaps)
    rendered_blits = (
        _render_sprite_blit(
            sprite,
            _bitmap_for_sprite(sprite, bitmaps),
        )
        for sprite in scene.sprites
    )
    sprite_blits = "\n\n".join(blit for blit in rendered_blits if blit is not None)
    bitmap_destroys = "\n".join(_render_bitmap_destroy(bitmap) for bitmap in reversed(bitmaps))

    return f'''/* Generated by Godot2Amiga - M6.2 multi-sprite scene. */

#include "generated_project.h"

#include <ace/managers/blit.h>
#include <ace/managers/key.h>
#include <ace/managers/system.h>
#include <ace/managers/viewport/simplebuffer.h>
#include <ace/utils/bitmap.h>
#include <ace/utils/extview.h>
#include <ace/utils/palette.h>

static tView *s_pView;
static tVPort *s_pViewport;
static tSimpleBufferManager *s_pBuffer;
{bitmap_declarations}
static UBYTE s_isRunning;

#define GENERIC_MAIN_LOOP_CONDITION s_isRunning
#include <ace/generic/main.h>

void genericCreate(void) {{
    keyCreate();

    s_pView = viewCreate(0, TAG_DONE);

    s_pViewport = vPortCreate(
        0,
        TAG_VPORT_VIEW,
        s_pView,
        TAG_VPORT_BPP,
        {bpp},
        TAG_DONE
    );

    s_pBuffer = simpleBufferCreate(
        0,
        TAG_SIMPLEBUFFER_VPORT,
        s_pViewport,
        TAG_SIMPLEBUFFER_BITMAP_FLAGS,
        {bitmap_flags},
        TAG_SIMPLEBUFFER_IS_DBLBUF,
        0,
        TAG_DONE
    );

    paletteLoadFromPath(
        "{palette_path}",
        s_pViewport->pPalette,
        {color_count}
    );

{bitmap_loads}

{sprite_blits}

    blitWait();

    s_isRunning = 1;
    systemUnuse();
    viewLoad(s_pView);
}}

void genericProcess(void) {{
    keyProcess();

    if (keyUse(KEY_ESCAPE)) {{
        s_isRunning = 0;
        return;
    }}

    vPortWaitForEnd(s_pViewport);
}}

void genericDestroy(void) {{
    systemUse();

{bitmap_destroys}

    viewDestroy(s_pView);
    keyDestroy();
}}
'''


__all__ = [
    "RuntimeBitmap",
    "render_runtime_scene_main_c",
    "unique_runtime_bitmaps",
]
