"""ACE visual smoke-test source generation."""

from __future__ import annotations


def render_visual_smoke_test_main_c() -> str:
    """Render a minimal visible ACE program for end-to-end verification."""
    return """/* Generated by Godot2Amiga. */

#include "generated_project.h"

#include <ace/managers/key.h>
#include <ace/managers/system.h>
#include <ace/managers/viewport/simplebuffer.h>

int main(void) {
    tView *pView;
    tVPort *pViewport;
    tSimpleBufferManager *pBuffer;

    systemCreate();
    keyCreate();

    pView = viewCreate(
        0,
        TAG_VIEW_GLOBAL_PALETTE,
        1,
        TAG_END
    );

    pViewport = vPortCreate(
        0,
        TAG_VPORT_VIEW,
        pView,
        TAG_VPORT_BPP,
        1,
        TAG_END
    );

    pBuffer = simpleBufferCreate(
        0,
        TAG_SIMPLEBUFFER_VPORT,
        pViewport,
        TAG_SIMPLEBUFFER_BITMAP_FLAGS,
        BMF_CLEAR,
        TAG_END
    );

    if (!pView || !pViewport || !pBuffer) {
        keyDestroy();
        systemDestroy();
        return 1;
    }

    /*
     * The cleared one-bitplane bitmap displays palette color zero.
     * Bright blue makes successful startup immediately visible.
     */
    pViewport->pPalette[0] = 0x000F;
    pViewport->pPalette[1] = 0x0FF0;

    systemUnuse();
    viewLoad(pView);

    while (!keyCheck(KEY_ESCAPE)) {
        keyProcess();
        vPortWaitForEnd(pViewport);
    }

    systemUse();
    viewDestroy(pView);
    keyDestroy();
    systemDestroy();

    return 0;
}
"""
