"""ACE interactive runtime smoke-test source generation."""

from __future__ import annotations


def render_visual_smoke_test_main_c() -> str:
    """Render a visible and interactive ACE runtime smoke test."""
    return """/* Generated by Godot2Amiga. */

#include "generated_project.h"

#include <ace/managers/key.h>
#include <ace/managers/system.h>
#include <ace/managers/viewport/simplebuffer.h>

int main(void) {
    tView *pView;
    tVPort *pViewport;
    tSimpleBufferManager *pBuffer;
    UBYTE ubSpaceWasDown = 0;
    UBYTE ubAlternateColor = 0;

    systemCreate();
    keyCreate();

    pView = viewCreate(
        0,
        TAG_VIEW_GLOBAL_PALETTE,
        1,
        TAG_END
    );

    pViewport = vPortCreate(
        0,
        TAG_VPORT_VIEW,
        pView,
        TAG_VPORT_BPP,
        1,
        TAG_END
    );

    pBuffer = simpleBufferCreate(
        0,
        TAG_SIMPLEBUFFER_VPORT,
        pViewport,
        TAG_SIMPLEBUFFER_BITMAP_FLAGS,
        BMF_CLEAR,
        TAG_END
    );

    if (!pView || !pViewport || !pBuffer) {
        keyDestroy();
        systemDestroy();
        return 1;
    }

    /*
     * Both entries begin as blue so any stray one-bits remain invisible.
     * SPACE toggles both entries between blue and green.
     */
    pViewport->pPalette[0] = 0x0008;
    pViewport->pPalette[1] = 0x0008;

    systemUnuse();
    viewLoad(pView);

    while (!keyCheck(KEY_ESCAPE)) {
        UBYTE ubSpaceDown = keyCheck(KEY_SPACE);

        if (ubSpaceDown && !ubSpaceWasDown) {
            ubAlternateColor = !ubAlternateColor;

            if (ubAlternateColor) {
                pViewport->pPalette[0] = 0x0080;
                pViewport->pPalette[1] = 0x0080;
            }
            else {
                pViewport->pPalette[0] = 0x0008;
                pViewport->pPalette[1] = 0x0008;
            }

            viewLoad(pView);
        }

        ubSpaceWasDown = ubSpaceDown;
        vPortWaitForEnd(pViewport);
    }

    systemUse();
    viewDestroy(pView);
    keyDestroy();
    systemDestroy();

    return 0;
}
"""
