"""ACE M4.4 blitter-based runtime smoke-test generation."""

from __future__ import annotations


def render_visual_smoke_test_main_c() -> str:
    """Render a stable interactive ACE program using the blitter manager."""
    return r"""/* Generated by Godot2Amiga. */

#include "generated_project.h"

#include <ace/managers/blit.h>
#include <ace/managers/key.h>
#include <ace/managers/system.h>
#include <ace/managers/viewport/simplebuffer.h>

#define G2A_SCREEN_WIDTH 320
#define G2A_SCREEN_HEIGHT 256
#define G2A_GLYPH_WIDTH 5
#define G2A_GLYPH_HEIGHT 7
#define G2A_GLYPH_SCALE 2
#define G2A_GLYPH_ADVANCE ((G2A_GLYPH_WIDTH + 1) * G2A_GLYPH_SCALE)

static UBYTE g2aGlyphRow(char c, UBYTE ubRow) {
    static const UBYTE s_ubBlank[7] = {
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
    };
    static const UBYTE s_ubA[7] = {
        0x0E, 0x11, 0x11, 0x1F, 0x11, 0x11, 0x11
    };
    static const UBYTE s_ubC[7] = {
        0x0E, 0x11, 0x10, 0x10, 0x10, 0x11, 0x0E
    };
    static const UBYTE s_ubD[7] = {
        0x1E, 0x11, 0x11, 0x11, 0x11, 0x11, 0x1E
    };
    static const UBYTE s_ubE[7] = {
        0x1F, 0x10, 0x10, 0x1E, 0x10, 0x10, 0x1F
    };
    static const UBYTE s_ubG[7] = {
        0x0E, 0x11, 0x10, 0x17, 0x11, 0x11, 0x0F
    };
    static const UBYTE s_ubH[7] = {
        0x11, 0x11, 0x11, 0x1F, 0x11, 0x11, 0x11
    };
    static const UBYTE s_ubI[7] = {
        0x0E, 0x04, 0x04, 0x04, 0x04, 0x04, 0x0E
    };
    static const UBYTE s_ubL[7] = {
        0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x1F
    };
    static const UBYTE s_ubM[7] = {
        0x11, 0x1B, 0x15, 0x15, 0x11, 0x11, 0x11
    };
    static const UBYTE s_ubN[7] = {
        0x11, 0x19, 0x15, 0x13, 0x11, 0x11, 0x11
    };
    static const UBYTE s_ubO[7] = {
        0x0E, 0x11, 0x11, 0x11, 0x11, 0x11, 0x0E
    };
    static const UBYTE s_ubP[7] = {
        0x1E, 0x11, 0x11, 0x1E, 0x10, 0x10, 0x10
    };
    static const UBYTE s_ubR[7] = {
        0x1E, 0x11, 0x11, 0x1E, 0x14, 0x12, 0x11
    };
    static const UBYTE s_ubS[7] = {
        0x0F, 0x10, 0x10, 0x0E, 0x01, 0x01, 0x1E
    };
    static const UBYTE s_ubT[7] = {
        0x1F, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04
    };
    static const UBYTE s_ubX[7] = {
        0x11, 0x11, 0x0A, 0x04, 0x0A, 0x11, 0x11
    };
    static const UBYTE s_ub2[7] = {
        0x0E, 0x11, 0x01, 0x02, 0x04, 0x08, 0x1F
    };

    const UBYTE *pRows = s_ubBlank;

    switch (c) {
        case 'A': pRows = s_ubA; break;
        case 'C': pRows = s_ubC; break;
        case 'D': pRows = s_ubD; break;
        case 'E': pRows = s_ubE; break;
        case 'G': pRows = s_ubG; break;
        case 'H': pRows = s_ubH; break;
        case 'I': pRows = s_ubI; break;
        case 'L': pRows = s_ubL; break;
        case 'M': pRows = s_ubM; break;
        case 'N': pRows = s_ubN; break;
        case 'O': pRows = s_ubO; break;
        case 'P': pRows = s_ubP; break;
        case 'R': pRows = s_ubR; break;
        case 'S': pRows = s_ubS; break;
        case 'T': pRows = s_ubT; break;
        case 'X': pRows = s_ubX; break;
        case '2': pRows = s_ub2; break;
        default: break;
    }

    return pRows[ubRow];
}

static void g2aDrawFrame(
    tBitMap *pBitmap,
    WORD wX,
    WORD wY,
    WORD wWidth,
    WORD wHeight,
    UBYTE ubColor
) {
    blitRect(pBitmap, wX, wY, wWidth, 2, ubColor);
    blitRect(pBitmap, wX, wY + wHeight - 2, wWidth, 2, ubColor);
    blitRect(pBitmap, wX, wY, 2, wHeight, ubColor);
    blitRect(pBitmap, wX + wWidth - 2, wY, 2, wHeight, ubColor);
}

static void g2aDrawChar(
    tBitMap *pBitmap,
    WORD wX,
    WORD wY,
    char c,
    UBYTE ubColor
) {
    UBYTE ubRow;

    for (ubRow = 0; ubRow < G2A_GLYPH_HEIGHT; ++ubRow) {
        UBYTE ubBits = g2aGlyphRow(c, ubRow);
        UBYTE ubColumn;

        for (ubColumn = 0; ubColumn < G2A_GLYPH_WIDTH; ++ubColumn) {
            if (ubBits & (1U << (G2A_GLYPH_WIDTH - 1 - ubColumn))) {
                blitRect(
                    pBitmap,
                    wX + ubColumn * G2A_GLYPH_SCALE,
                    wY + ubRow * G2A_GLYPH_SCALE,
                    G2A_GLYPH_SCALE,
                    G2A_GLYPH_SCALE,
                    ubColor
                );
            }
        }
    }
}

static void g2aDrawText(
    tBitMap *pBitmap,
    WORD wX,
    WORD wY,
    const char *szText,
    UBYTE ubColor
) {
    while (*szText) {
        g2aDrawChar(pBitmap, wX, wY, *szText, ubColor);
        wX += G2A_GLYPH_ADVANCE;
        ++szText;
    }
}

int main(void) {
    tView *pView;
    tVPort *pViewport;
    tSimpleBufferManager *pBuffer;
    tBitMap *pDrawBitmap;
    UBYTE ubSpaceWasDown = 0;
    UBYTE ubAlternateColor = 0;

    systemCreate();
    keyCreate();
    blitManagerCreate();

    pView = viewCreate(
        0,
        TAG_VIEW_GLOBAL_PALETTE,
        1,
        TAG_END
    );

    pViewport = vPortCreate(
        0,
        TAG_VPORT_VIEW,
        pView,
        TAG_VPORT_BPP,
        1,
        TAG_END
    );

    pBuffer = simpleBufferCreate(
        0,
        TAG_SIMPLEBUFFER_VPORT,
        pViewport,
        TAG_SIMPLEBUFFER_BITMAP_FLAGS,
        BMF_CLEAR,
        TAG_END
    );

    if (!pView || !pViewport || !pBuffer || !pBuffer->pFront) {
        if (pView) {
            viewDestroy(pView);
        }
        blitManagerDestroy();
        keyDestroy();
        systemDestroy();
        return 1;
    }

    pDrawBitmap = pBuffer->pFront;

    /*
     * Draw the complete static frame before enabling the view.
     * No direct bitplane writes and no per-frame buffer processing.
     */
    blitRect(
        pDrawBitmap,
        0,
        0,
        G2A_SCREEN_WIDTH,
        G2A_SCREEN_HEIGHT,
        0
    );
    g2aDrawFrame(pDrawBitmap, 24, 48, 272, 144, 1);
    g2aDrawText(pDrawBitmap, 94, 76, "GODOT2AMIGA", 1);
    g2aDrawText(pDrawBitmap, 46, 108, "SPACE CHANGES COLOR", 1);
    g2aDrawText(pDrawBitmap, 106, 140, "ESC EXITS", 1);
    blitWait();

    pViewport->pPalette[0] = 0x0008;
    pViewport->pPalette[1] = 0x0FFF;

    systemUnuse();
    viewLoad(pView);

    while (!keyCheck(KEY_ESCAPE)) {
        UBYTE ubSpaceDown = keyCheck(KEY_SPACE);

        if (ubSpaceDown && !ubSpaceWasDown) {
            ubAlternateColor = !ubAlternateColor;
            pViewport->pPalette[0] = (
                ubAlternateColor ? 0x0080 : 0x0008
            );
            viewLoad(pView);
        }

        ubSpaceWasDown = ubSpaceDown;
        vPortWaitForEnd(pViewport);
    }

    systemUse();
    viewDestroy(pView);
    blitManagerDestroy();
    keyDestroy();
    systemDestroy();

    return 0;
}
"""
