"""Deterministic source templates for the ACE backend."""

from __future__ import annotations


def c_string(value: str) -> str:
    """Escape a Python string for use inside a C string literal."""
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def render_main_c(project_name: str) -> str:
    escaped_name = c_string(project_name)
    return f"""/* Generated by Godot2Amiga. */

#include "generated_project.h"

#include <ace/managers/log.h>

int main(void) {{
    logWrite("Godot2Amiga: {escaped_name}\\n");
    return 0;
}}
"""


def render_generated_header(project_name: str, project_id: str) -> str:
    escaped_name = c_string(project_name)
    escaped_id = c_string(project_id)
    return f"""#pragma once

#define G2A_PROJECT_NAME "{escaped_name}"
#define G2A_PROJECT_ID "{escaped_id}"

const char *g2a_project_name(void);
const char *g2a_project_id(void);
"""


def render_generated_source() -> str:
    return """/* Generated by Godot2Amiga. */

#include "generated_project.h"

const char *g2a_project_name(void) {
    return G2A_PROJECT_NAME;
}

const char *g2a_project_id(void) {
    return G2A_PROJECT_ID;
}
"""


def render_cmake(project_id: str) -> str:
    return f"""cmake_minimum_required(VERSION 3.20)

project({project_id} C)

if(NOT DEFINED G2A_ACE_ROOT)
    message(FATAL_ERROR "G2A_ACE_ROOT must point to an ACE source checkout")
endif()

if(NOT EXISTS "${{G2A_ACE_ROOT}}/CMakeLists.txt")
    message(FATAL_ERROR "G2A_ACE_ROOT does not contain ACE CMakeLists.txt")
endif()

add_subdirectory("${{G2A_ACE_ROOT}}" "${{CMAKE_BINARY_DIR}}/ace")

add_executable(${{PROJECT_NAME}}
    src/main.c
    src/generated_project.c
)

target_include_directories(${{PROJECT_NAME}} PRIVATE include)
target_link_libraries(${{PROJECT_NAME}} PRIVATE ace)

set_target_properties(${{PROJECT_NAME}} PROPERTIES
    C_STANDARD 11
    C_STANDARD_REQUIRED YES
    C_EXTENSIONS YES
)
"""


def render_makefile(project_id: str) -> str:
    return f"""CMAKE ?= cmake
BUILD_DIR ?= .g2a-build
ACE_ROOT ?=
TOOLCHAIN_FILE ?=
JOBS ?= 1
TARGET ?= {project_id}

.PHONY: configure build clean

configure:
	$(CMAKE) -S . -B $(BUILD_DIR) \
		-DCMAKE_TOOLCHAIN_FILE=$(TOOLCHAIN_FILE) \
		-DG2A_ACE_ROOT=$(ACE_ROOT)

build: configure
	$(CMAKE) --build $(BUILD_DIR) --parallel $(JOBS)

clean:
	rm -rf $(BUILD_DIR)
"""
