"""Deterministic source templates for the ACE backend."""

from __future__ import annotations


def c_string(value: str) -> str:
    """Escape a Python string for use inside a C string literal."""
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def render_main_c(project_name: str) -> str:
    escaped_name = c_string(project_name)
    return f"""/* Generated by Godot2Amiga. */

#include "generated_project.h"

#include <stdio.h>

int main(void) {{
    puts("Godot2Amiga: {escaped_name}");
    return 0;
}}
"""


def render_generated_header(project_name: str, project_id: str) -> str:
    escaped_name = c_string(project_name)
    escaped_id = c_string(project_id)
    return f"""#pragma once

#define G2A_PROJECT_NAME "{escaped_name}"
#define G2A_PROJECT_ID "{escaped_id}"

const char *g2a_project_name(void);
const char *g2a_project_id(void);
"""


def render_generated_source() -> str:
    return """/* Generated by Godot2Amiga. */

#include "generated_project.h"

const char *g2a_project_name(void) {
    return G2A_PROJECT_NAME;
}

const char *g2a_project_id(void) {
    return G2A_PROJECT_ID;
}
"""


def render_cmake(project_id: str) -> str:
    return f"""cmake_minimum_required(VERSION 3.20)

project({project_id} C)

add_executable(${{PROJECT_NAME}}
    src/main.c
    src/generated_project.c
)

target_include_directories(${{PROJECT_NAME}} PRIVATE include)
"""


def render_makefile(project_id: str) -> str:
    return f"""CC ?= m68k-amigaos-gcc
CFLAGS ?= -O2 -Wall -Wextra -Iinclude
TARGET ?= {project_id}

SOURCES := src/main.c src/generated_project.c

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(SOURCES)
	$(CC) $(CFLAGS) -o $@ $(SOURCES)

clean:
	rm -f $(TARGET)
"""
